### ISSUE TITLE
new release pls

### ISSUE THREAD

**Issue by joaocc** [yadutaf/docker-machine-driver-ovh#10]
Hi. Could you please publish a new release with the latest fixes? Thx

**Comment by yadutaf** [comment]
done.

**Comment by joaocc** [comment]
Hi. Did you push the released binaries to github already? I can only find the previous version (0.5.0 from Nov). Thx

**Comment by yadutaf** [comment]
Can you confirm the lastest fix works as expected before pushing ?

**Comment by joaocc** [comment]
Yes, I tested with commit (d6fb1bdbe56036728093db17724c6ffa128b1c90) and it seems to work. Thx

**Comment by yadutaf** [comment]
Done (https://github.com/yadutaf/docker-machine-driver-ovh/releases/tag/v1.0.0)
