### ISSUE TITLE
Release packaging with tar and `docker-machine` compatible naming

### ISSUE THREAD

**Issue by y8** [yadutaf/docker-machine-driver-ovh#21]
Hi.

Since docker-machine looks for `docker-machine-driver-<driver_name>`, current packaging is a bit hard to use. See this thread: https://forums.rancher.com/t/add-machine-driver/2209/6

My suggestion is to do as @vincent99 saying: pack releases in the tarball with platform name (i.e `docker-machine-driver-ovh-vX.Y.Z-linux-amd64.tar.gz`, but put the binary as `docker-machine-driver-ovh` inside the archive. 

This will really help to ease deployment using this driver.

Thank you.

**Comment by yadutaf** [comment]
I like that idea. Would you be interested in submitting a PR for the release script?

**Comment by yadutaf** [comment]
I like that idea. Would you be interested in submitting a PR for the release script?

**Comment by y8** [comment]
Sure. But I can put it only in the next sprint, so it's need to wait till the next week. It's okay?

**Comment by yadutaf** [comment]
Absolutely!

**Comment by y8** [comment]
Just pushed the #23. Sorry for a delay.

**Comment by yadutaf** [comment]
No worry. Thanks for the PR!

**Comment by yadutaf** [comment]
And closing since the PR has been merge.
