### ISSUE TITLE
use with rancher

### ISSUE THREAD

**Issue by fredleger** [yadutaf/docker-machine-driver-ovh#32]
Hi,

Would love to use this driver with rancher.

Tried and even if setup went smoothly i'm facing this error message after "pre-checks":

```
Error with pre-create check: "Get https://eu.api.ovh.com/1.0/auth/time: dial tcp 213.186.33.30:443: getsockopt: connection refused"
 ```

<img width="275" alt="capture d ecran 2017-05-19 a 17 26 45" src="https://cloud.githubusercontent.com/assets/2778741/26254919/6f7a0dc6-3cb8-11e7-8bf7-861f36570406.png">

**Comment by fredleger** [comment]
my bad, it was related to the consumer key missing.

**Comment by yadutaf** [comment]
No worry. Thanks for taking the time to report and dig !
