### ISSUE TITLE
Installation: Not working on MAC

### ISSUE THREAD

**Issue by Izhaki** [yadutaf/docker-machine-driver-ovh#35]
Based on this [SO answer](https://stackoverflow.com/a/21506074/1179377) go no longer sets the `$GOPATH`, not on a Mac at least.

So Following the instructions creates an empty symbolic link and then when you run the correct command, it complains that the file already exists.

Replacing `$GOPATH` with `$HOME/go` works:

    ln -s $HOME/go/bin/docker-machine-driver-ovh /usr/local/bin/docker-machine-driver-ovh

**Comment by yadutaf** [comment]
Hmmm, seems hackish to me... What about this ?

```
ln -s $(go env GOPATH)/bin/docker-machine-driver-ovh /usr/local/bin/docker-machine-driver-ovh
```

**Comment by Izhaki** [comment]
That looks great.

Question is: Would this work on platforms other than Mac?

**Comment by yadutaf** [comment]
I see no reason it should not work on *NIX platforms. Windows is a different story. But this driver was never tested on windows anyway

**Comment by yadutaf** [comment]
Here is the PR https://github.com/yadutaf/docker-machine-driver-ovh/pull/37/files

**Comment by Izhaki** [comment]
Looks great.
