### ISSUE TITLE
New project structure

### ISSUE THREAD

**Issue by xlucas** [yadutaf/docker-machine-driver-ovh#4]
What if the structure switched to the following :

```
docker-machine-driver-ovh
  ├── cmd 
  │    └── machine-driver-ovh.go (former main.go)
  ├── docs
  │    └── <images, contributing howto, additional docs>
  ├── driver
  │     ├── ovh.go (former driver.go)
  │     └── ovhcloud
  │           └── <OVH cloud api helpers & wrappers>  (former api.go)  
  ├── script
  └── <usual stuff: readme, travis, makefile, vendoring ...>
```

Then `docker-machine-driver-ovh/driver/ovhcloud` would hold what's in `api.go` but split per type and/or nature.

What do you think ?

**Comment by yadutaf** [comment]
docs / driver / scripts --> makes definitively sense to me.

machine-driver-ovh.go --> won't it break "go get" ?

**Comment by xlucas** [comment]
If you mean in order to install the driver then yes it will break the way it works for now since no buildable go file will be found in the base directory. If that's the preferable way to ship the driver then main.go should be kept as is.

In case this is not important, a common pattern is to use a makefile that, among other things, gonna contain a build target which leverage `go build -o` to generate the appropriate binary in `$GOPATH/bin`.

**Comment by yadutaf** [comment]
OK. Imho api.go should migrate to go-ovh once the base is mature.

**Comment by xlucas** [comment]
I agree with that.

**Comment by yadutaf** [comment]
Closing as inactive. Feel free to re-open
