### ISSUE TITLE
Be able to provide existing ssh key

### ISSUE THREAD

**Issue by batmat** [yadutaf/docker-machine-driver-ovh#5]
Like with the `generic` docker-machine driver, it would be great to be able to provide an existing ssh key[pair] and use for node creation.

Indeed, as the current impl generates as many keys as there are nodes, this can get problematic for example if the cloud infra (like openstack@ovh) has quota on ssh keypairs :-).

More context: https://twitter.com/oyadutaf/status/676344444573102080

**Comment by yadutaf** [comment]
Done, on upcoming apiv6 branch. Enjoy.

**Comment by batmat** [comment]
Great! Thanks!

2015-12-14 22:16 GMT+01:00 Jean-Tiare Le Bigot notifications@github.com:

> Closed #5 https://github.com/yadutaf/docker-machine-driver-ovh/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yadutaf/docker-machine-driver-ovh/issues/5#event-491492890
> .

## 

Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !
