### ISSUE TITLE
docker-compose for ovh

### ISSUE THREAD

**Issue by joaocc** [yadutaf/docker-machine-driver-ovh#6]
Hi,
Can we deploy docker-compose configs to ovh using this driver?
Thx

**Comment by yadutaf** [comment]
This driver provisions hosts on OVH Cloud offer with standard docker pre-installed. Once installed, you can use it as any other host provisioned with docker machine, hence with docker-compose or docker-swarm.

**Comment by joaocc** [comment]
Thx!
