### ISSUE TITLE
Impossible to install the package

### ISSUE THREAD

**Issue by hadri3n** [yadutaf/docker-machine-driver-ovh#7]
_go install_ or _go get_ bring up the same error :

```
hadrien@ubuntu:~/Dev$ go install github.com/yadutaf/docker-machine-driver-ovh

src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:214: undefined: log.WithField
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:223: undefined: log.WithField
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:258: undefined: log.WithField
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:304: undefined: log.WithField
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:323: undefined: log.WithFields
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:323: undefined: log.Fields
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:338: undefined: log.WithField
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:347: undefined: log.WithFields
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:347: undefined: log.Fields
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:380: undefined: log.WithField
src/github.com/yadutaf/docker-machine-driver-ovh/driver.go:380: too many errors
hadrien@ubuntu:~/Dev$ 
```

I'm not a go specialist though.

**Comment by hadri3n** [comment]
Attempted with go 1.5

**Comment by Nbushkov** [comment]
same error (go 1.5)

**Comment by yadutaf** [comment]
I'm currently working on merging multiple go-ovh implementations. When this is done, I'll get back on maintaining this plugin and propose it as an official OVH project. In the mean time, this project is considered experimental, although I'll consider merging in PRs

**Comment by yadutaf** [comment]
You're right. It does not build. It sucks. This is caused by this re-factoring: https://github.com/docker/machine/commit/1079735af8a76a73fe98f501d12c784e0f94665d. Hopefully https://github.com/yadutaf/docker-machine-driver-ovh/commit/607500c62a12e35f90232c5946c29debc2566450 upgrades accordingly.

This is a quick and dirty patch, let me know if it helps.
